name: stickerdocs_core
description: StickerDocs Core
version: 1.0.0+1
homepage: https://github.com/stickerdocs/core

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.1
  convert: ^3.1.1
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.0
  http: ^1.1.0
  logger: ^2.0.1
  mime: ^1.0.4
  mutex: ^3.0.1
  path: ^1.8.3
  path_provider: ^2.1.0
  sodium: ^2.1.1
  sodium_libs: ^2.1.1+1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  uuid: 3.0.5
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter: